[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  
# Skip dependency installation phase since Netlify will handle it automatically
[build.processing]
  skip_processing = false

